/*-------------------------------------------------------------------------
 *
 * pg_trace_etw.h
 *	  ETW (Event Tracing for Windows) backend for the static probes.
 *
 * With the "etw" build option (Windows only), the TRACE_POSTGRESQL_* macros
 * are generated by Gen_etw_probes.pl and expand to TraceLogging events on a
 * single "PostgreSQL" provider.  This header declares the provider, the
 * keyword bits that group the events, and the per-process register and
 * unregister entry points.  Without the option those entry points are no-op
 * macros, so callers need no #ifdef.
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * src/include/utils/pg_trace_etw.h
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_TRACE_ETW_H
#define PG_TRACE_ETW_H

#ifdef USE_ETW

/*
 * <windows.h> is already included via win32_port.h.  Add the TraceLogging API
 * and the WINEVENT_LEVEL_* constants the generated macros use.
 */
#include <winmeta.h>
#include <TraceLoggingProvider.h>

/*
 * The "PostgreSQL" provider.  The name and GUID are a stable identity that
 * saved capture profiles depend on, so neither changes across releases.  The
 * GUID literal (9ca0b6e3-55e4-406b-84b0-9c61060e0e5a) is in pg_trace_etw.c.
 */
TRACELOGGING_DECLARE_PROVIDER(g_hPostgresProvider);

/*
 * Keyword bits.  Each probe is tagged with one of these so a consumer can
 * enable one subsystem at a time; the high bits are reserved.
 */
#define PG_KW_QUERY			0x0000000000000001ULL
#define PG_KW_TRANSACTION	0x0000000000000002ULL
#define PG_KW_LOCK			0x0000000000000004ULL
#define PG_KW_BUFFER		0x0000000000000008ULL
#define PG_KW_STORAGE		0x0000000000000010ULL
#define PG_KW_WAL			0x0000000000000020ULL
#define PG_KW_CHECKPOINT	0x0000000000000040ULL
#define PG_KW_SORT			0x0000000000000080ULL

/* Register or unregister the provider for the current process. */
extern void pg_trace_etw_register(void);
extern void pg_trace_etw_unregister(void);

#else							/* !USE_ETW */

#define pg_trace_etw_register()		((void) 0)
#define pg_trace_etw_unregister()	((void) 0)

#endif							/* USE_ETW */

#endif							/* PG_TRACE_ETW_H */
