/*-------------------------------------------------------------------------
 *
 * pg_trace_etw.h
 *	  ETW (Event Tracing for Windows) backend for PostgreSQL static probes.
 *
 * When PostgreSQL is built with the "etw" option (Windows only), the
 * TRACE_POSTGRESQL_* probe macros are generated by Gen_etw_probes.pl and
 * expand to TraceLogging events fired against a single "PostgreSQL" ETW
 * provider.  This header declares that provider, the keyword bits used to
 * group events, and the per-process register/unregister entry points.
 *
 * Consumers (wpr, wpa, PerfView, logman, xperf) filter on the tuple
 * (provider, level, keyword).  See doc/src/sgml/monitoring.sgml for the
 * keyword and level layout.
 *
 * On builds without ETW the lifecycle entry points become no-ops, so callers
 * need not guard them with #ifdef.
 *
 * Copyright (c) 2026, PostgreSQL Global Development Group
 *
 * src/include/utils/pg_trace_etw.h
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_TRACE_ETW_H
#define PG_TRACE_ETW_H

#ifdef USE_ETW

/* win32_port.h already includes <windows.h>; add the TraceLogging API. */
#include <windows.h>
#include <winmeta.h>			/* WINEVENT_LEVEL_* for the generated macros */
#include <TraceLoggingProvider.h>

/*
 * The "PostgreSQL" ETW provider.  Both the name and the GUID are a stable,
 * public identity that consumers and saved capture profiles reference, so
 * neither changes across releases.  The GUID literal is in pg_trace_etw.c.
 *
 *	   Provider GUID: 9ca0b6e3-55e4-406b-84b0-9c61060e0e5a
 */
TRACELOGGING_DECLARE_PROVIDER(g_hPostgresProvider);

/*
 * Keyword bits.  Each probe is tagged with exactly one of these, so a consumer
 * can enable a subsystem at a time.  The 64-bit keyword space leaves the high
 * bits reserved for future growth.
 */
#define PG_KW_QUERY			0x0000000000000001ULL
#define PG_KW_TRANSACTION	0x0000000000000002ULL
#define PG_KW_LOCK			0x0000000000000004ULL
#define PG_KW_BUFFER		0x0000000000000008ULL
#define PG_KW_STORAGE		0x0000000000000010ULL
#define PG_KW_WAL			0x0000000000000020ULL
#define PG_KW_CHECKPOINT	0x0000000000000040ULL
#define PG_KW_SORT			0x0000000000000080ULL

/*
 * Register/unregister the provider for the current process.  The handle is
 * process-local, so every process that may fire a probe registers at startup.
 */
extern void pg_trace_etw_register(void);
extern void pg_trace_etw_unregister(void);

#else							/* !USE_ETW */

#define pg_trace_etw_register()		((void) 0)
#define pg_trace_etw_unregister()	((void) 0)

#endif							/* USE_ETW */

#endif							/* PG_TRACE_ETW_H */
