#-------------------------------------------------------------------------
# Perl script to create a TraceLogging-based probes.h for ETW (Event Tracing
# for Windows) builds.
#
# It reads probes.d (the argument types, shared with the DTrace backend) and
# probes_etw.dat (the ETW keyword/level/field-name policy) and emits, on
# stdout, the same TRACE_POSTGRESQL_* macro names the DTrace and dummy backends
# produce -- so probe call sites are identical across all backends.  The only
# difference is the right-hand side: here each macro expands to a
# TraceLoggingWrite()/TraceLoggingProviderEnabled() pair.
#
# probes.d stays the single source of truth for argument count, order, and
# type.  This script cross-checks probes_etw.dat against it and dies if the two
# disagree (a probe missing from either file, an unmapped type, or a field-name
# count that does not match the argument count).
#
# Copyright (c) 2026, PostgreSQL Global Development Group
#
# src/backend/utils/Gen_etw_probes.pl
#-------------------------------------------------------------------------

use strict;
use warnings FATAL => 'all';

# probes.d type -> [ TraceLogging macro, cast applied to the argument value ].
# The cast is '' for none, 'STRING' for the NULL-guarded string case, or a C
# cast token to prepend (used to widen MSVC's 32-bit 'long' to 64 bits).
my %type_map = (
	'LocalTransactionId' => [ 'TraceLoggingUInt32', '' ],
	'BlockNumber' => [ 'TraceLoggingUInt32', '' ],
	'Oid' => [ 'TraceLoggingUInt32', '' ],
	'unsigned int' => [ 'TraceLoggingUInt32', '' ],
	'LWLockMode' => [ 'TraceLoggingInt32', '' ],
	'LOCKMODE' => [ 'TraceLoggingInt32', '' ],
	'ForkNumber' => [ 'TraceLoggingInt32', '' ],
	'int' => [ 'TraceLoggingInt32', '' ],
	'bool' => [ 'TraceLoggingUInt8', '' ],
	'unsigned char' => [ 'TraceLoggingUInt8', '' ],
	'long' => [ 'TraceLoggingInt64', '(LONGLONG)' ],
	'const char *' => [ 'TraceLoggingString', 'STRING' ],);

my %keyword_token = map { $_ => "PG_KW_$_" }
  qw(QUERY TRANSACTION LOCK BUFFER STORAGE WAL CHECKPOINT SORT);

my %level_token = (
	INFO => 'WINEVENT_LEVEL_INFO',
	VERBOSE => 'WINEVENT_LEVEL_VERBOSE',);

my ($probes_d, $policy_dat) = @ARGV;
defined $probes_d && defined $policy_dat
  or die "usage: $0 probes.d probes_etw.dat\n";

# ---- parse probes.d: name -> arrayref of argument type strings -------------
my @order;    # preserve probes.d order for output
my %args;
open(my $pd, '<', $probes_d) or die "could not open \"$probes_d\": $!\n";
while (my $line = <$pd>)
{
	next unless $line =~ /^\s*probe\s+([^(]+)\(([^)]*)\)\s*;/;
	my ($name, $arglist) = ($1, $2);
	$name =~ s/\s+//g;
	$arglist =~ s/^\s+|\s+$//g;
	my @types;
	if (length $arglist)
	{
		for my $t (split /\s*,\s*/, $arglist)
		{
			$t =~ s/^\s+|\s+$//g;
			$t =~ s/\s+/ /g;
			push @types, $t;
		}
	}
	push @order, $name;
	$args{$name} = \@types;
}
close $pd;

# ---- parse probes_etw.dat: name -> {keyword, level, fields[]} --------------
my %policy;
open(my $pf, '<', $policy_dat) or die "could not open \"$policy_dat\": $!\n";
while (my $line = <$pf>)
{
	$line =~ s/#.*$//;
	next unless $line =~ /\S/;
	my @col = split ' ', $line;
	my $name = shift @col;
	my $kw = shift @col;
	my $lvl = shift @col;
	defined $kw && defined $lvl
	  or die "$policy_dat: probe \"$name\" is missing keyword/level\n";
	exists $keyword_token{$kw}
	  or die "$policy_dat: probe \"$name\" has unknown keyword \"$kw\"\n";
	exists $level_token{$lvl}
	  or die "$policy_dat: probe \"$name\" has unknown level \"$lvl\"\n";
	$policy{$name} = { keyword => $kw, level => $lvl, fields => [@col] };
}
close $pf;

# ---- cross-validate the two files ------------------------------------------
for my $name (@order)
{
	exists $policy{$name}
	  or die "probe \"$name\" is in $probes_d but missing from $policy_dat\n";
	my $nargs = scalar @{ $args{$name} };
	my $nfields = scalar @{ $policy{$name}{fields} };
	$nargs == $nfields
	  or die "probe \"$name\": $probes_d has $nargs argument(s) but "
	  . "$policy_dat names $nfields field(s)\n";
	for my $t (@{ $args{$name} })
	{
		exists $type_map{$t}
		  or die "probe \"$name\": no ETW type mapping for \"$t\"\n";
	}
}
for my $name (sort keys %policy)
{
	exists $args{$name}
	  or die "probe \"$name\" is in $policy_dat but missing from $probes_d\n";
}

# ---- emit the header -------------------------------------------------------
print <<'EOH';
/*
 * This file is generated by Gen_etw_probes.pl from probes.d and
 * probes_etw.dat.  Do not edit by hand.
 *
 * It maps the TRACE_POSTGRESQL_* probe macros to ETW (Event Tracing for
 * Windows) TraceLogging events.  The macro names are identical to those of the
 * DTrace and dummy backends, so probe call sites are unchanged.
 */

#include "utils/pg_trace_etw.h"

EOH

for my $name (@order)
{
	my @types = @{ $args{$name} };
	my $pol = $policy{$name};
	my @fields = @{ $pol->{fields} };
	my $kw = $keyword_token{ $pol->{keyword} };
	my $lvl = $level_token{ $pol->{level} };

	# event name: collapse double underscores, lower case (matches DTrace)
	(my $event = $name) =~ s/__/_/g;

	# macro name: TRACE_POSTGRESQL_ + upper-cased event name
	(my $macro = $event) =~ tr/a-z/A-Z/;
	$macro = "TRACE_POSTGRESQL_$macro";

	# macro parameters are positional (arg1, arg2, ...) to match call sites;
	# the human-readable field labels come from probes_etw.dat.
	my @params = map { "arg$_" } 1 .. scalar(@types);
	my $paramlist = join(', ', @params);

	print "/* probe $name(" . join(', ', @types) . "); */\n";
	print "#define $macro($paramlist) \\\n";
	print "\tTraceLoggingWrite(g_hPostgresProvider, \"$event\", \\\n";
	print "\t\tTraceLoggingKeyword($kw), \\\n";
	print "\t\tTraceLoggingLevel($lvl)";
	for my $i (0 .. $#types)
	{
		my ($tlmacro, $cast) = @{ $type_map{ $types[$i] } };
		my $arg = $params[$i];
		my $field = $fields[$i];
		my $value;
		if ($cast eq 'STRING')
		{
			# TraceLoggingString requires a non-NULL pointer; guard it.
			$value = "(($arg) ? ($arg) : \"\")";
		}
		elsif (length $cast)
		{
			$value = "$cast($arg)";
		}
		else
		{
			$value = "($arg)";
		}
		print ", \\\n\t\t$tlmacro($value, \"$field\")";
	}
	print ")\n";

	print "#define ${macro}_ENABLED() \\\n";
	print "\tTraceLoggingProviderEnabled(g_hPostgresProvider, $lvl, $kw)\n\n";
}
