CREATE FUNCTION get_counter_value()
RETURNS int
AS 'MODULE_PATHNAME'
LANGUAGE C STRICT;

CREATE FUNCTION get_counter_description()
RETURNS text
AS 'MODULE_PATHNAME'
LANGUAGE C STRICT;

CREATE FUNCTION show_server_pool()
RETURNS text
AS 'MODULE_PATHNAME'
LANGUAGE C STRICT;

CREATE FUNCTION count_servers()
RETURNS int
AS 'MODULE_PATHNAME'
LANGUAGE C STRICT;

CREATE FUNCTION get_pool_setting(text)
RETURNS text
AS 'MODULE_PATHNAME'
LANGUAGE C STRICT;